### PR TITLE
Added support for error messages and fixed Project.Delete interface to return a bool

### PR DESCRIPTION
**Pull request by michaKFromParis**

### CODE REVIEW

**Comment by Scooletz** [comment]
I can take a1a840c and 882f630 but cannot accept the last one. I'll get a closer look and comment on this.

**Comment by Scooletz** [comment]
Can you check https://github.com/Scooletz/NGitLab/tree/master-p ? I've made one commit to put your changes to the project client. Are you ok with this? If yes, i'll merge the master-p branch and close this pull request.

**Comment by michaKFromParis** [comment]
Hi Szymon,

The last commit was not intended to be pushed to your repo. It just got
added automatically.
I completely agree it needs to be discussed as it opens the door to a
broader discussion.

I felt like I was breaking the nice Data Interfaces that you've been
maintaining by adding Code to the models and only made the Api object
static for prototyping purposes. Pushing the object down to the models is
the first road I thought about too but this object only lives with one
client and as I general pattern, I avoid keeping multiple references on
objects that are shared to avoid potential GC problems in the future. So
I'm unsure of the best way to go.

In broader terms, so far, you kept your Data interfaces very clean and left
the code in the various Clients. But from a functional point of view, when
it comes to enabling services on a project or any other sub-entity
instances, it's from the model object that I want to access it.
What would you consider the most elegant way to handle this?

I would really like to keep our dev in sync and define a common strategy.

Keep up the good work,

M

On Tue, Feb 10, 2015 at 9:48 PM, Szymon Kulec <notifications@github.com>
wrote:

> Can you check https://github.com/Scooletz/NGitLab/tree/master-p ? I've
> made one commit to put your changes to the project client. Are you ok with
> this? If yes, i'll merge the master-p branch and close this pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Scooletz/NGitLab/pull/15#issuecomment-73780583>.
>



-- 
Michel Courtine | CEO | iVoltage
+33 6 189 354 89 | michaK@ivoltage.me
http://ivoltage.me

**Comment by Scooletz** [comment]
Thank you for the clarification. I'd go with the two first commits then. You can consider my branch as a proposal for your future work if you want to.

From the beginning I wanted to keep the separation between operations and their results but if it's leading us to copy properties over to new methods we may consider other options as well.

You intrigued me with the GC aspect. I'm into performance as well so if you could share some thoughts or point to a blog post, anything which covers your concern I'd be more than happy to read it. I cannot see what's wrong with passing the reference and hold it in multiple places.

I'll push the version with your two commits later in the evening, then I'll close this pull request.

**Comment by Scooletz** [comment]
Two commits merged with: 84788e5d32b6ac7b89cd061a139ede76592fd576
Will open an issue about further design choices.

**Pull request closed without merging**
