### PR TITLE
Fixed Exception when deserializing Json Iso8601 containing Timezone info

### PR DESCRIPTION
**Pull request by michaKFromParis**
When gitlab is configured with a timezone info, the json DateTime objects are serialized including the timezone.
A DateTime string usually formatted as:

2014-10-10T19:32:33.655

becomes

2014-10-10T19:32:33.655**+02:00**

and crashes the Json deserializer

Tested with gitlab 7.7.2

### CODE REVIEW

**Comment by Scooletz** [comment]
Thx for posting that. Is it possible to get a failing test and ... a pull
request resolving this issue ? :)

Regards

**Comment by michaKFromParis** [comment]
Hi,

certainly. but I don't see any tests in the repo...
Also, I realized in the PR that the old commits that were not squashed
together a while ago appeared again.
Do you know how to resolve this on my side ?

Best,

M

On Thu, Feb 5, 2015 at 8:02 PM, Szymon Kulec <notifications@github.com>
wrote:

> Thx for posting that. Is it possible to get a failing test and ... a pull
> request resolving this issue ? :)
>
> Regards
>
> On Thu, Feb 5, 2015 at 3:58 AM, Michel Courtine <notifications@github.com>
> wrote:
>
> > When gitlab is configured with a timezone info, the json DateTime objects
> > are serialized including the timezone.
> > A DateTime string usually formatted as:
> >
> > 2014-10-10T19:32:33.655
> >
> > becomes
> >
> > 2014-10-10T19:32:33.655*+02:00*
> >
> > and crashes the Json deserializer
> >
> > Tested with gitlab 7.7.2
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/Scooletz/NGitLab/pull/13
> > Commit Summary
> >
> > - set ToolsVersion to 4.0 in NGitLab.csproj & NGitLab.Tests.csproj to
> > support Xamarin
> > - Added AvatarUrl property to User Model. Seems to only work with
> > users that uploaded their own pictures. Doesn't seem to report gravatar
> > urls...
> > - Merge branch 'master' of https://github.com/michaKFromParis/NGitLab
> > - Fixed spacing
> > - Fixed spacing again...
> > - Merge branch 'master' of https://github.com/michaKFromParis/NGitLab
> > - Merge branch 'master' of https://github.com/Scooletz/NGitLab
> > - Fixed Exception when deserializing Json Iso8601 containing Timezone
> > info
> >
> > File Changes
> >
> > - *M* NGitLab/NGitLab/Impl/SimpleJson.cs
> > <https://github.com/Scooletz/NGitLab/pull/13/files#diff-0> (1)
> >
> > Patch Links:
> >
> > - https://github.com/Scooletz/NGitLab/pull/13.patch
> > - https://github.com/Scooletz/NGitLab/pull/13.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Scooletz/NGitLab/pull/13>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Scooletz/NGitLab/pull/13#issuecomment-73105385>.
>



-- 
Michel Courtine | CEO | iVoltage
+33 6 189 354 89 | michaK@ivoltage.me
http://ivoltage.me

**Comment by michaKFromParis** [comment]
Ooops... Sorry. Found the Test project. Will implement a test when I get a minute

**Comment by Scooletz** [comment]
I can help in merge during weekend. I just have to take a look at your
branch.

Waiting for your commit! :)

Have a nice day
6 lut 2015 03:06 "Michel Courtine" <notifications@github.com> napisał(a):

**Comment by michaKFromParis** [comment]
I think it would also be nice to add an option to disable SSL Certificates verification. Maybe as an optional flag to Connect to optionally call:
ServicePointManager.ServerCertificateValidationCallback = new System.Net.Security.RemoteCertificateValidationCallback(delegate { return true; });

What do you think?

**Comment by Scooletz** [comment]
I can't remember now. Wouldn't this apply the ServicePointManager.
ServerCertificateValidationCallback set to the whole application? Can it be
done locally maybe?
Still, it would be useful to get this. There's plenty of companies using
self-signed certs.

**Comment by michaKFromParis** [comment]
It does set it globally for the application and I don't know of any way to define it locally. But still, it's worth giving an option to the user to remind him of the potential issue and just set a flag to false.

**Comment by Scooletz** [comment]
I'm not strongly opinionated about this aspect. You're probably right -
providing an option within the library can be helpful.

**Pull request merged**
