### PR TITLE
Implement issues, milestones and notes interaction

### PR DESCRIPTION
**Pull request by laskoviymishka**
Implement issues, milestones and notes interaction.

### CODE REVIEW

**Comment by hellboy81** [comment]
please accept this pull request

**Comment by Scooletz** [comment]
I've tweeted the info that ai can't no longer maintain this & looking for a
new maintainer. Are you ready to be one?
22 lut 2016 10:02 "hellboy81" <notifications@github.com> napisał(a):

**Comment by hellboy81** [comment]
> Are you ready to be one?

yes!

**Comment by Scooletz** [comment]
@hellboy81 DM me on Twitter or send an email pls to discuss this.

**Pull request closed without merging**
